[package]
name = "sdle_class"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
pluribus = "0.1.0"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
zeromq = "0.4.1"
